### ISSUE TITLE
support watchanimeattheoffice.com

### ISSUE THREAD

**Issue by vtheskeleton** [sefinek24/is-discord-invite#1]
https://watchanimeattheoffice.com/ is another discord domain

**Comment by sefinek24** [comment]
Thanks

**Comment by sefinek24** [comment]
https://github.com/sefinek24/is-discord-invite/compare/v1.0.9...v1.0.10#diff-af95cb6f5f65fe70216ddce70325e785438d5aaff956a0666ebf46ef6402f526R11
