### ISSUE TITLE
Online verification does not support {GuildName}-{GuildId} style invites

### ISSUE THREAD

**Issue by PlaryWasTaken** [sefinek24/is-discord-invite#3]
Invites such as `https://discord.com/invite/otakus-br-828415559183630357` are considered invalid when using online verification but are valid. Curl command used to test: `curl https://discord.com/api/invites/otakus-br-828415559183630357`, returns: 
```json
{"type":0,"code":"otakus-br-828415559183630357","expires_at":null,"flags":2,"guild":{"id":"828415559183630357","name":"Otakus BR","splash":"c0dcaf3851bd800e708c5028f7c320a7","banner":"8fbf5b1850ae89ede905cdb6a64e145e","description":"Seja bem-vindo","icon":"5aec47171ff29ac8f59ce7a66daf4c9f","features":["INVITE_SPLASH","DISCOVERABLE","COMMUNITY","SOUNDBOARD","THREE_DAY_THREAD_ARCHIVE","ENABLED_DISCOVERABLE_BEFORE","PREVIEW_ENABLED","TEXT_IN_VOICE_ENABLED","AUTO_MODERATION","NEWS","ANIMATED_ICON","CHANNEL_ICON_EMOJIS_GENERATED","MEMBER_VERIFICATION_GATE_ENABLED","GUILD_WEB_PAGE_VANITY_URL"],"verification_level":1,"vanity_url_code":"otakus-br-828415559183630357","nsfw_level":0,"nsfw":false,"premium_subscription_count":2},"guild_id":"828415559183630357","channel":{"id":"833860205460324433","type":0,"name":"\u0b68\u0b67\ud83d\udccb\u1dd4\u1dd4\u1dd4\u30fbregras\u02da\u208a"}}

**Comment by sefinek24** [comment]
The API link you provided is essentially an API link, and it should not be treated as an invitation.

Everything is functioning normally on my end. You should think about the objective of your exercises.

![](https://cdn.sefinek.net/static/20.01.2024/Postman_4q3UZ8dkBHnO.png)

**Comment by PlaryWasTaken** [comment]
![image](https://github.com/sefinek24/is-discord-invite/assets/70018287/e00b3129-73af-4e45-b083-d98d6ddc3261)
A bit scuffed but shows the problem in question

**Comment by PlaryWasTaken** [comment]
The online regex didnt match for invites that follow this schema

**Comment by sefinek24** [comment]
Now it makes sense

**Comment by PlaryWasTaken** [comment]
@sefinek24 i noticed a mistake on the regex i commited `(https:\/\/discord\.(?:gg|com)(?:\/invite)?\/[a-zA-Z0-9\-]+(?:-\d{18,19})?)` covers more cases, since invites can also appear as discord.gg/invite/{InviteCode} not only as discord.gg/{InviteCode}

**Comment by sefinek24** [comment]
Try to fix this in https://github.com/sefinek24/is-discord-invite/pull/5

**Comment by PlaryWasTaken** [comment]
Ill open a PR to merge into `revert-4-main`
